AWSTemplateFormatVersion: 2010-09-09
Description: Cloud formation template for Flexible Database Backup
Mappings:
  ParametersAndSecretsLayer:
    us-east-1:
        ParametersAndSecrets: arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    us-east-2:
        ParametersAndSecrets: arn:aws:lambda:us-east-2:590474943231:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    us-west-1: 
        ParametersAndSecrets: arn:aws:lambda:us-west-1:997803712105:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    us-west-2:
        ParametersAndSecrets: arn:aws:lambda:us-west-2:345057560386:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    af-south-1:
        ParametersAndSecrets: arn:aws:lambda:af-south-1:317013901791:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    ap-east-1:
        ParametersAndSecrets: arn:aws:lambda:ap-east-1:768336418462:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    ap-southeast-3:
        ParametersAndSecrets: arn:aws:lambda:ap-southeast-3:490737872127:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    ap-south-1:
        ParametersAndSecrets: arn:aws:lambda:ap-south-1:176022468876:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    ap-northeast-3:
        ParametersAndSecrets: arn:aws:lambda:ap-northeast-3:576959938190:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    ap-northeast-2:
        ParametersAndSecrets: arn:aws:lambda:ap-northeast-2:738900069198:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    ap-southeast-1:
        ParametersAndSecrets: arn:aws:lambda:ap-southeast-1:044395824272:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    ap-southeast-2:
        ParametersAndSecrets: arn:aws:lambda:ap-southeast-2:665172237481:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    ap-northeast-1:
        ParametersAndSecrets: arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    ca-central-1:
        ParametersAndSecrets: arn:aws:lambda:ca-central-1:200266452380:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    eu-central-1:
        ParametersAndSecrets: arn:aws:lambda:eu-central-1:187925254637:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    eu-west-1:
        ParametersAndSecrets: arn:aws:lambda:eu-west-1:015030872274:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    eu-west-2:
        ParametersAndSecrets: arn:aws:lambda:eu-west-2:133256977650:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11
    eu-south-1:
        ParametersAndSecrets: arn:aws:lambda:eu-south-1:325218067255:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    eu-west-3:
        ParametersAndSecrets: arn:aws:lambda:eu-west-3:780235371811:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    eu-north-1:
        ParametersAndSecrets: arn:aws:lambda:eu-north-1:427196147048:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    me-south-1:
        ParametersAndSecrets: arn:aws:lambda:me-south-1:832021897121:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
    sa-east-1:
        ParametersAndSecrets: arn:aws:lambda:sa-east-1:933737806257:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:8
      
Parameters:
    version:
      Type: String
      Description: "[Required]. The version of Cloud Formation template that is desired to be used. The version must be available in the S3 bucket. Default value: latest. Example: v2.3.4"
      Default: "latest"
    baseURL:
      Type: String
      Description: "[Required]. Base URL link used to connect to API. Example: https://api-k8s-cloudapi.qa.redislabs.com."
      Default: https://api-k8s-cloudapi.qa.redislabs.com
    subscriptionId:
      Type: Number
      Description: "[Required]. The ID of the Flexible Subscription that contains the Flexible Database that you want to backup. Example: 163199"
    databaseId:
      Type: Number
      Description: "[Required]. The ID of the Flexible Database that you want to backup. Example: 163199"
    regionName:
      Type: String
      Description: "[Optional]. Name of cloud provider region where the local database is located. When backing up an active-active database, backup is done separately for each local database at a specified region."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Parameters:
          - version
          - baseURL
          - subscriptionId
          - dbname
          - regionName

Conditions:
  regionNameCondition: !Not [!Equals [!Ref regionName, ""]]

Resources:
  # StepFunctionsAllowLambda:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName: 
  #       Fn::Sub: StepFunctionsAllowLambdaForDatabaseBackup-${AWS::Region}-${AWS::StackName}
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Effect: Allow
  #           Principal:
  #             Service:
  #             - states.amazonaws.com
  #           Action :
  #           - sts:AssumeRole
  #     Path: "/"
  #     Policies:
  #     - PolicyName: StepFunctionsAllowLambdaForDatabaseBackup
  #       PolicyDocument:
  #         Version: '2012-10-17'
  #         Statement:
  #         - Effect: Allow
  #           Action:
  #           - lambda:InvokeFunction
  #           Resource: "*"

  # MyStateMachine:
  #   Type: AWS::StepFunctions::StateMachine
  #   DependsOn: 
  #     - FlexibleDatabaseBackupCheckState
  #     - FlexibleDatabaseBackupCFResponse
  #   Properties:
  #     RoleArn: !GetAtt StepFunctionsAllowLambda.Arn
  #     StateMachineName:
  #       Fn::Sub: "FlexibleDatabaseBackup-StateMachine-${AWS::Region}-${AWS::StackName}"
  #     DefinitionString: !Sub |-
  #       {
  #         "Comment": "A description of my state machine",
  #         "StartAt": "CheckDatabaseStatus",
  #         "States": {
  #           "CheckDatabaseStatus": {
  #             "Type": "Task",
  #             "Resource": "arn:aws:states:::lambda:invoke",
  #             "OutputPath": "$.Payload",
  #             "Parameters": {
  #               "Payload.$": "$",
  #               "FunctionName": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:FlexibleDatabaseBackup-CheckState-${AWS::Region}-${AWS::StackName}"
  #             },
  #             "Retry": [
  #               {
  #                 "ErrorEquals": [
  #                   "Lambda.ServiceException",
  #                   "Lambda.AWSLambdaException",
  #                   "Lambda.SdkClientException",
  #                   "Lambda.TooManyRequestsException"
  #                 ],
  #                 "IntervalSeconds": 2,
  #                 "MaxAttempts": 6,
  #                 "BackoffRate": 2
  #               }
  #             ],
  #             "Next": "Choice"
  #           },
  #           "Choice": {
  #             "Type": "Choice",
  #             "Choices": [
  #               {
  #                 "Not": {
  #                   "Variable": "$.db_status",
  #                   "StringEquals": "active"
  #                 },
  #                 "Next": "Wait"
  #               }
  #             ],
  #             "Default": "GiveCFResponse"
  #           },
  #           "GiveCFResponse": {
  #             "Type": "Task",
  #             "Resource": "arn:aws:states:::lambda:invoke",
  #             "OutputPath": "$.Payload",
  #             "Parameters": {
  #               "Payload.$": "$",
  #               "FunctionName": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:FlexibleDatabaseBackup-CFResponse-${AWS::Region}-${AWS::StackName}"
  #             },
  #             "Retry": [
  #               {
  #                 "ErrorEquals": [
  #                   "Lambda.ServiceException",
  #                   "Lambda.AWSLambdaException",
  #                   "Lambda.SdkClientException",
  #                   "Lambda.TooManyRequestsException"
  #                 ],
  #                 "IntervalSeconds": 2,
  #                 "MaxAttempts": 6,
  #                 "BackoffRate": 2
  #               }
  #             ],
  #             "End": true
  #           },
  #           "Wait": {
  #             "Type": "Wait",
  #             "Seconds": 300,
  #             "Next": "CheckDatabaseStatus"
  #           }
  #         }
  #       }

  RequestsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: RequestsLayer
      Description: RequestsLayer
      Content:
        S3Bucket: redis-cicd
        S3Key:
          Fn::Join:
            - ""
            - - "Flexible-Database/"
              - !Ref version
              - "/requests_layer.zip"
      CompatibleRuntimes:
        - python3.7
        - python3.8
        - python3.9
        - python3.10
        - python3.11
      CompatibleArchitectures: 
        - arm64
        - x86_64

  SecretsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: SecretsLayer
      Description: SecretsLayer
      Content:
        S3Bucket: redis-cicd
        S3Key:
          Fn::Join:
            - ""
            - - "Flexible-Database/"
              - !Ref version
              - "/secrets_layer.zip"
      CompatibleRuntimes:
        - python3.7
        - python3.8
        - python3.9
        - python3.10
        - python3.11
      CompatibleArchitectures: 
        - arm64
        - x86_64

  RedisLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        Fn::Sub: FlexibleDatabaseBackupLambdaExecutionRole-${AWS::Region}-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: FlexibleDatabaseBackupLambdaExecutionRole
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:PutRetentionPolicy
            - logs:CreateLogGroup
            - states:*
            - cloudformation:*
            - secretsmanager:GetSecretValue
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:DeleteObject
            Resource: "*"

  FlexibleDatabaseBackupHandlerEventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties: 
      FunctionName: !Ref FlexibleDatabaseBackupHandler
      MaximumRetryAttempts: 0
      Qualifier: $LATEST
  # FlexibleDatabaseBackupCheckStateEventInvokeConfig:
  #   Type: AWS::Lambda::EventInvokeConfig
  #   Properties: 
  #     FunctionName: !Ref FlexibleDatabaseBackupCheckState
  #     MaximumRetryAttempts: 0
  #     Qualifier: $LATEST
  # FlexibleDatabaseBackupCFResponseEventInvokeConfig:
  #   Type: AWS::Lambda::EventInvokeConfig
  #   Properties: 
  #     FunctionName: !Ref FlexibleDatabaseBackupCFResponse
  #     MaximumRetryAttempts: 0
  #     Qualifier: $LATEST

  FlexibleDatabaseBackupHandler:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: "FlexibleDatabaseBackup-Handler-${AWS::Region}-${AWS::StackName}"
      Architectures: 
        - arm64
      Runtime: python3.10
      Handler: FlexibleDatabaseBackup-Handler.lambda_handler
      Timeout: 300
      Role: !GetAtt RedisLambdaExecutionRole.Arn
      Layers:
        - !Ref RequestsLayer
        - !Ref SecretsLayer
        - !FindInMap [ParametersAndSecretsLayer, !Ref "AWS::Region", ParametersAndSecrets]
      Code:
        S3Bucket: redis-cicd
        S3Key:
          Fn::Join:
            - ""
            - - "Flexible-Database/"
              - !Ref version
              - "/FlexibleDatabaseBackup-Handler.zip"

  # FlexibleDatabaseBackupCheckState:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName:
  #       Fn::Sub: "FlexibleDatabaseBackup-CheckState-${AWS::Region}-${AWS::StackName}"
  #     Architectures: 
  #       - arm64
  #     Runtime: python3.10
  #     Handler: FlexibleDatabaseBackup-CheckState.lambda_handler
  #     Timeout: 300
  #     Role: !GetAtt RedisLambdaExecutionRole.Arn
  #     Layers:
  #       - !Ref RequestsLayer
  #       - !Ref SecretsLayer
  #       - !FindInMap [ParametersAndSecretsLayer, !Ref "AWS::Region", ParametersAndSecrets]
  #     Code:
  #       S3Bucket: redis-cicd
  #       S3Key:
  #         Fn::Join:
  #           - ""
  #           - - "Flexible-Database/"
  #             - !Ref version
  #             - "/FlexibleDatabaseBackup-CheckState.zip"
    
  # FlexibleDatabaseBackupCFResponse:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName:
  #       Fn::Sub: "FlexibleDatabaseBackup-CFResponse-${AWS::Region}-${AWS::StackName}"
  #     Architectures: 
  #       - arm64
  #     Runtime: python3.10
  #     Handler: FlexibleDatabaseBackup-CFResponse.lambda_handler
  #     Timeout: 300
  #     Role: !GetAtt RedisLambdaExecutionRole.Arn
  #     Layers:
  #       - !Ref RequestsLayer
  #       - !Ref SecretsLayer
  #       - !FindInMap [ParametersAndSecretsLayer, !Ref "AWS::Region", ParametersAndSecrets]
  #     Code:
  #       S3Bucket: redis-cicd
  #       S3Key:
  #         Fn::Join:
  #           - ""
  #           - - "Flexible-Database/"
  #             - !Ref version
  #             - "/FlexibleDatabaseBackup-CFResponse.zip"
            
  Redis:
    Type: Custom::FlexibleDatabaseBackup-Handler
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt FlexibleDatabaseBackupHandler.Arn
      version:                             !Ref version
      baseURL:                             !Ref baseURL
      subscriptionId:                      !Ref subscriptionId
      databaseId:                          !Ref databaseId
      regionName:                          !If [regionNameCondition, !Ref regionName, !Ref "AWS::NoValue"]

Outputs:
  SubscriptionId:
    Description: Subscription ID used for the current stack
    Value: !GetAtt Redis.SubscriptionId
  DatabaseId:
    Description: Database ID for current stack
    Value: !GetAtt Redis.DatabaseId
  PostCall:
    Description: POST API call sent as a JSON to Redis Cloud
    Value: !GetAtt Redis.PostCall